### ISSUE TITLE
MimiFAIRv1_6_2 dependency 

### ISSUE THREAD

**Issue by karldw** [anthofflab/MimiFUND-MimiFAIR-Flat.jl#7]
Hello,

I was looking around a bit at FAIR integration, and I saw that the dependency `MimiFAIRv1_6_2` is no longer available from Frank's public repos. (There is a [work-in-progress version](https://github.com/FrankErrickson/MimiFAIRv2.jl) of FAIR 2.0 though).
Not a big deal, I just thought I should flag!

https://github.com/anthofflab/MimiFUND-MimiFAIR-Flat.jl/blob/62f15d3c8d466dd78c32b203db278b5f5ca6e177/Manifest.toml#L688-L694

**Comment by davidanthoff** [comment]
https://github.com/FrankErrickson/MimiFAIRv1_6_2.jl is there, right? It is now actually registered in the general Julia registry, so you can just add it via `pkg> add MimiFAIRv1_6_2`.
